#test ci
branches:
  only:
  - master

language: java
jdk:
  - openjdk8


sudo: false
install: true

script:
  - mvn install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
